const vuePlugin = require("eslint-plugin-vue");
const js = require("@eslint/js");
const prettier = require("eslint-config-prettier");

module.exports = [
  js.configs.recommended,
  ...vuePlugin.configs["flat/essential"],
  prettier,
  {
    ignores: [
      "android/**",
      "ios/**",
      "node_modules/**",
      "dist/**",
      ".quasar/**",
      "src-capacitor/**",
      "src-pwa/**",
      ".eslintrc.cjs",
    ],
  },
  {
    files: ["src/**/*.{vue,js,ts}", "*.{vue,js,ts}"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ga: "readonly",
        cordova: "readonly",
        __statics: "readonly",
        __QUASAR_SSR__: "readonly",
        __QUASAR_SSR_SERVER__: "readonly",
        __QUASAR_SSR_CLIENT__: "readonly",
        __QUASAR_SSR_PWA__: "readonly",
        process: "readonly",
        Capacitor: "readonly",
        chrome: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        location: "readonly",
        window: "readonly",
        document: "readonly",
        Promise: "readonly",
        FormData: "readonly",
        URLSearchParams: "readonly",
        navigator: "readonly",
        self: "readonly",
        global: "readonly",
        btoa: "readonly",
        atob: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        indexedDB: "readonly",
        Element: "readonly",
        SVGElement: "readonly",
        MouseEvent: "readonly",
        TouchEvent: "readonly",
        ClipboardEvent: "readonly",
        DataTransfer: "readonly",
        FileList: "readonly",
        History: "readonly",
        getComputedStyle: "readonly",
        browser: "readonly",
      },
    },
    rules: {
      "prefer-promise-reject-errors": "off",
      "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
      "no-unused-vars": "warn",
      "vue/multi-word-component-names": "off",
      "no-undef": "off",
    },
  },
  {
    files: ["tests/**/*.{js,ts}"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "commonjs",
      globals: {
        test: "readonly",
        expect: "readonly",
        describe: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        it: "readonly",
        jest: "readonly",
        page: "readonly",
      },
    },
    rules: {
      "no-undef": "off",
    },
  },
  {
    files: ["scripts/**/*.{js,mjs,cjs}", "version.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "commonjs",
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        Buffer: "readonly",
        global: "readonly",
      },
    },
    rules: {
      "no-undef": "off",
      "no-unused-vars": "off",
    },
  },
  {
    files: ["src/boot/**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        window: "readonly",
        document: "readonly",
        Promise: "readonly",
        Capacitor: "readonly",
        Platform: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "no-empty-pattern": "off",
    },
  },
];
